name:  Feature request / Предложить новую функциональность 
description:  Suggest an idea or function for this project / Предложить новую идею или функциональность в программе

body:
  - type: markdown
    attributes:
      value: |
        If you think of a great function or circumvention method which is missing from the program, go ahead and suggest it here. But first make sure to search exiting tickets.
        Если вы придумали новую функцию или метод обхода, которого еще нет в программе, напишите о нем подробнее здесь. Но сначала убедитесь с помощью поиска, что такого запроса еще не было.
  - type: checkboxes
    id: ensure
    attributes:
      label: I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
      options:
        - label: I've made sure there's no existing feature request / Я убедился, что такой функциональности еще никто не предлагал
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your feature / Опишите ваше предложение
    validations:
      required: true
